-- The screening snapshot. Each run keeps its own rows, so earlier snapshots stay available for history.
CREATE TABLE IF NOT EXISTS snapshot_run (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    universe          VARCHAR(40)              NOT NULL,
    snapshot_date     DATE                     NOT NULL,
    started_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at       TIMESTAMP WITH TIME ZONE,
    status            VARCHAR(20)              NOT NULL,
    symbols_requested INT                      NOT NULL,
    symbols_stored    INT                      NOT NULL DEFAULT 0,
    symbols_failed    INT                      NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS fundamentals_snapshot (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id               BIGINT                   NOT NULL REFERENCES snapshot_run (id),
    symbol               VARCHAR(40)              NOT NULL,
    company_name         VARCHAR(300),
    industry_group       VARCHAR(40)              NOT NULL,
    classification_basis VARCHAR(1000),
    snapshot_date        DATE                     NOT NULL,
    captured_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (run_id, symbol)
);

-- One row per metric, with its DataStatus as the research layer produced it.
CREATE TABLE IF NOT EXISTS snapshot_metric (
    snapshot_id      BIGINT         NOT NULL REFERENCES fundamentals_snapshot (id),
    metric           VARCHAR(60)    NOT NULL,
    metric_value     DECIMAL(30, 8),
    metric_unit      VARCHAR(20),
    display          VARCHAR(200)   NOT NULL,
    data_status      VARCHAR(20)    NOT NULL,
    status_reason    VARCHAR(4000),
    period_label     VARCHAR(200),
    source           VARCHAR(1000),
    calculation      VARCHAR(2000),
    unchecked_reason VARCHAR(2000),
    PRIMARY KEY (snapshot_id, metric)
);

CREATE TABLE IF NOT EXISTS snapshot_failure (
    run_id BIGINT        NOT NULL REFERENCES snapshot_run (id),
    symbol VARCHAR(40)   NOT NULL,
    reason VARCHAR(4000) NOT NULL
);
