package com.ashish.stockresearch.research.report;

import com.ashish.stockresearch.research.model.AnnualFinancials;
import com.ashish.stockresearch.research.model.AnnualRatios;
import com.ashish.stockresearch.research.model.CalendarYearReturn;
import com.ashish.stockresearch.research.model.CompanyProfile;
import com.ashish.stockresearch.research.model.DataGap;
import com.ashish.stockresearch.research.model.DataQualityIssue;
import com.ashish.stockresearch.research.model.FinancialDataPoint;
import com.ashish.stockresearch.research.model.FinancialSummary;
import com.ashish.stockresearch.research.model.HeadlineFinancials;
import com.ashish.stockresearch.research.model.HistoricalPerformance;
import com.ashish.stockresearch.research.model.QuarterlyResult;
import com.ashish.stockresearch.research.model.ReportedFinancials;
import com.ashish.stockresearch.research.sector.SectorContext;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Set;

/**
 * Renders a {@link StockResearchReport} as Markdown, deterministically.
 * FACTS, OBSERVATIONS, DATA GAPS and SOURCES are produced here from the
 * structured data, so the model never re-types a number; only the
 * INTERPRETATION section comes from the model, and it is labelled as
 * analysis.
 *
 * Every financial value is shown with its period, calculation status, raw
 * provider value and unit, and source field. Values that depend on a field
 * in a DATA_CONFLICT are tagged so no reader mistakes them for settled.
 */
@Component
public class ResearchReportRenderer {

    /**
     * Which fields are in a DATA_CONFLICT, and who the facts are for: the reader sees conflicting
     * values tagged, the model sees them withheld.
     */
    private record Mask(Set<String> fields, boolean forModel) {

        boolean covers(FinancialDataPoint p) {
            return p.dependsOnFields().stream().anyMatch(fields::contains);
        }
    }

    static final String CONFLICT_TAG = " [DATA_CONFLICT]";
    /** What the model sees in place of a value that depends on a conflicting field. */
    static final String WITHHELD_FOR_MODEL = "WITHHELD - depends on a field in a DATA_CONFLICT";

    public String render(StockResearchReport report, String interpretation) {
        Mask conflicted = new Mask(report.conflictedFields(), false);
        StringBuilder md = new StringBuilder();
        md.append("# Research report: ").append(report.companyName())
                .append(" (").append(report.symbol()).append(")\n\n");
        md.append("Generated ").append(report.generatedOn()).append(". Latest reported quarter: **")
                .append(report.latestReportedQuarter().label()).append("**");
        if (report.latestReportedQuarter().known()) {
            md.append(" (period ended ").append(report.latestReportedQuarter().end()).append(")");
        }
        md.append(".\n\n");
        renderConflicts(md, report);

        md.append("## 1. FACTS\n\n_Values supplied by the stated source (REPORTED) or computed by the application "
                + "from them (CALCULATED). Amounts are normalised to crore by the application only after the "
                + "source's own format confirmed the raw unit._\n\n");
        renderFacts(md, report, conflicted);

        md.append("## 2. OBSERVATIONS\n\n_Patterns directly visible in the facts, stated by the application. "
                + "They describe what the data shows, not why._\n\n");
        if (report.observations().isEmpty()) {
            md.append("- No observations could be derived from the available data.\n");
        }
        report.observations().forEach(o -> md.append("- ").append(o.statement()).append("\n"));
        if (!report.withheldObservations().isEmpty()) {
            md.append("\nWithheld because they depend on fields in a DATA_CONFLICT:\n");
            report.withheldObservations().forEach(o -> md.append("- ~~").append(o.statement()).append("~~\n"));
        }
        md.append("\n");

        md.append("## 3. RISKS / DATA GAPS\n\n");
        if (report.dataQualityIssues().isEmpty() && report.dataGaps().isEmpty()) {
            md.append("- No data gaps were recorded.\n");
        }
        for (DataQualityIssue issue : report.dataQualityIssues()) {
            md.append("- **").append(issue.type()).append(":** ").append(issue.message())
                    .append(" Fields: ").append(String.join(", ", issue.affectedFields())).append("\n");
        }
        for (DataGap gap : report.dataGaps()) {
            md.append("- **").append(gap.area()).append(" / ").append(gap.item()).append(":** ")
                    .append(gap.reason()).append("\n");
        }
        md.append("\n");

        md.append("## 4. INTERPRETATION\n\n_What the available evidence may suggest, generated by the language model "
                        + "from the sections above. This is interpretation, not fact, and not investment advice._\n\n")
                .append(interpretation == null || interpretation.isBlank()
                        ? "_No interpretation was generated._" : interpretation.strip())
                .append("\n\n");

        md.append("## 5. SOURCES\n\n");
        for (SourceReference source : report.sources()) {
            md.append("- ").append(source.source()).append(" [").append(source.sourceType()).append("] - ")
                    .append(source.covers());
            if (source.periodEnd() != null) {
                md.append("; period end ").append(source.periodEnd());
            }
            if (source.publishedAt() != null) {
                md.append("; results published ").append(source.publishedAt());
            }
            if (source.asOf() != null) {
                md.append("; as of ").append(source.asOf());
            }
            md.append("\n");
        }
        return md.toString();
    }

    /** What the model is given to interpret: conflicts first, then facts, observations and gaps. */
    public String renderEvidence(StockResearchReport report) {
        Mask conflicted = new Mask(report.conflictedFields(), true);
        StringBuilder md = new StringBuilder();
        md.append("Company: ").append(report.companyName()).append(" (").append(report.symbol()).append(")\n");
        md.append("Today: ").append(report.generatedOn()).append("; latest reported quarter: ")
                .append(report.latestReportedQuarter().label()).append("\n\n");
        renderConflicts(md, report);
        // Conflicting values are left out entirely: the model reports the conflict but gets nothing to
        // draw a conclusion from, and is never asked to reconcile the two sides.
        renderFacts(md, report, conflicted);
        md.append("OBSERVATIONS\n");
        report.observations().forEach(o -> md.append("- ").append(o.statement()).append("\n"));
        md.append("\nDATA GAPS AND DATA-QUALITY ISSUES\n");
        report.dataQualityIssues().forEach(i -> md.append("- ").append(i.type()).append(": ").append(i.message()).append("\n"));
        report.dataGaps().forEach(g -> md.append("- ").append(g.area()).append(" / ").append(g.item())
                .append(": ").append(g.reason()).append("\n"));
        return md.toString();
    }

    private void renderConflicts(StringBuilder md, StockResearchReport report) {
        List<DataQualityIssue> conflicts = report.dataQualityIssues().stream()
                .filter(i -> i.type() == DataQualityIssue.Type.DATA_CONFLICT).toList();
        if (conflicts.isEmpty()) {
            return;
        }
        md.append("> **DATA CONFLICT - read before the figures below.** The application has not chosen between the "
                + "conflicting values and draws no conclusions from them; values that depend on them are tagged"
                + CONFLICT_TAG + ".\n");
        for (DataQualityIssue conflict : conflicts) {
            md.append(">\n> - ").append(conflict.message()).append(" Fields: ")
                    .append(String.join(", ", conflict.affectedFields())).append("\n");
        }
        md.append("\n");
    }

    private void renderFacts(StringBuilder md, StockResearchReport report, Mask conflicted) {
        md.append("### Company\n\n");
        if (report.companyProfile().success()) {
            CompanyProfile p = report.companyProfile().companyProfile();
            md.append("| Item | Value | Status | Raw value (provider unit) | As of | Source field |\n")
                    .append("|---|---|---|---|---|---|\n");
            text(md, "Exchange", p.exchange(), "");
            text(md, "Sector", p.sector(), "assetProfile.sector");
            text(md, "Industry", p.industry(), "assetProfile.industry");
            text(md, "Employees", p.fullTimeEmployees() == null ? null : String.valueOf(p.fullTimeEmployees()),
                    "assetProfile.fullTimeEmployees");
            companyPoint(md, "Market capitalisation", p.marketCap(), conflicted);
            companyPoint(md, "Shares outstanding", p.sharesOutstanding(), conflicted);
            md.append("\n");
            if (p.businessSummary() != null) {
                md.append("Business summary (Yahoo Finance text): ").append(p.businessSummary()).append("\n\n");
            }
        } else {
            md.append("Company profile unavailable: ").append(report.companyProfile().message()).append("\n\n");
        }

        SectorContext sector = report.sectorContext();
        md.append("### Sector context\n\n_Industry group derived by the application from the classification below; the "
                + "metric guidance is application-supplied context, not data about this company._\n\n");
        md.append("- Industry group: **").append(sector.group()).append("** (").append(sector.basis()).append(")\n");
        md.append("- ").append(sector.note()).append("\n");
        if (!sector.lessMeaningfulMetrics().isEmpty()) {
            md.append("- Less meaningful for this group: ").append(String.join(", ", sector.lessMeaningfulMetrics()))
                    .append("\n");
        }
        if (!sector.sectorMetricsNotAvailable().isEmpty()) {
            md.append("- Sector metrics NOT SUPPORTED BY CURRENT DATA SOURCE: ")
                    .append(String.join(", ", sector.sectorMetricsNotAvailable())).append("\n");
        }
        md.append("\n");

        if (report.financials().success()) {
            renderFinancials(md, report.financials().financialSummary(), conflicted);
        } else {
            md.append("### Financials\n\nFinancial data unavailable: ").append(report.financials().message()).append("\n\n");
        }

        md.append("### Share-price history\n\n");
        if (report.historicalPerformance().success()) {
            renderHistory(md, report.historicalPerformance().historicalPerformance(), conflicted);
        } else {
            md.append("Price history unavailable: ").append(report.historicalPerformance().message()).append("\n\n");
        }

        md.append("### Shareholding\n\n");
        if (report.shareholding().success()) {
            md.append("Shareholding data retrieved; see structured report.\n\n");
        } else {
            md.append(ResearchReportService.SHAREHOLDING_UNAVAILABLE).append("\n\n");
        }
    }

    private void renderFinancials(StringBuilder md, FinancialSummary summary, Mask conflicted) {
        ReportedFinancials reported = summary.reported();
        HeadlineFinancials h = reported.headline();
        md.append("### Financials - headline figures (reporting currency: ")
                .append(reported.reportingCurrency() == null ? "UNKNOWN" : reported.reportingCurrency()).append(")\n\n");
        md.append("| Metric | Value | Period | Status | Raw value (provider unit) | Source field |\n")
                .append("|---|---|---|---|---|---|\n");
        for (FinancialDataPoint point : List.of(h.revenue(), h.netProfit(), summary.calculated().netProfitMarginTtmPercent(),
                h.netProfitMarginPercent(), h.operatingMarginPercent(), h.returnOnEquityPercent(),
                h.returnOnAssetsPercent(), h.ebitda(), h.freeCashFlow(), h.totalDebt(), h.totalCash(),
                h.debtToEquityPercent(), h.quarterlyRevenueGrowthYoyPercent(), h.quarterlyEarningsGrowthYoyPercent(),
                h.returnOnCapitalEmployedPercent())) {
            md.append("| ").append(point.metric()).append(" | ").append(value(point, conflicted)).append(" | ")
                    .append(point.period().label()).append(" | ").append(status(point)).append(" | ")
                    .append(raw(point, conflicted)).append(" | ").append(fields(point)).append(" |\n");
        }
        md.append("\n");

        if (!reported.recentQuarters().isEmpty()) {
            md.append("### Reported quarters (source fields: earnings.financialsChart / earnings.earningsChart)\n\n")
                    .append("| Quarter | Period end | Results published | Revenue | Net profit | EPS |\n")
                    .append("|---|---|---|---|---|---|\n");
            for (QuarterlyResult q : reported.recentQuarters()) {
                md.append("| ").append(q.period().label()).append(" | ").append(q.period().end()).append(" | ")
                        .append(q.revenue().source() != null && q.revenue().source().publishedAt() != null
                                ? q.revenue().source().publishedAt() : "UNKNOWN")
                        .append(" | ").append(value(q.revenue(), conflicted)).append(" | ")
                        .append(value(q.netProfit(), conflicted)).append(" | ")
                        .append(value(q.earningsPerShare(), conflicted)).append(" |\n");
            }
            md.append("\n");
        }

        List<AnnualFinancials> annual = reported.annualHistory();
        if (!annual.isEmpty()) {
            md.append("### Fiscal years (source fields: fundamentals-timeseries)\n\n")
                    .append("| Fiscal year | Period end | Revenue | Net profit | Shareholders' equity | Total assets | Total debt |\n")
                    .append("|---|---|---|---|---|---|---|\n");
            for (AnnualFinancials year : annual) {
                md.append("| ").append(year.period().label()).append(" | ").append(year.period().end()).append(" | ")
                        .append(value(year.revenue(), conflicted)).append(" | ")
                        .append(value(year.netProfit(), conflicted)).append(" | ")
                        .append(value(year.shareholdersEquity(), conflicted)).append(" | ")
                        .append(value(year.totalAssets(), conflicted)).append(" | ")
                        .append(value(year.totalDebt(), conflicted)).append(" |\n");
            }
            md.append("\n### Calculated per fiscal year (CALCULATED by the application)\n\n")
                    .append("| Fiscal year | Revenue YoY | Net profit YoY | Net margin | Operating margin | ROE | ROA | Debt / equity |\n")
                    .append("|---|---|---|---|---|---|---|---|\n");
            for (AnnualRatios r : summary.calculated().annual()) {
                md.append("| ").append(r.period().label());
                for (FinancialDataPoint p : List.of(r.revenueGrowthYoyPercent(), r.netProfitGrowthYoyPercent(),
                        r.netProfitMarginPercent(), r.operatingMarginPercent(), r.returnOnEquityPercent(),
                        r.returnOnAssetsPercent(), r.debtToEquityMultiple())) {
                    md.append(" | ").append(p.available() ? value(p, conflicted) : "n/a");
                }
                md.append(" |\n");
            }
            md.append("\nROE and ROA use average opening and closing balances where the prior year is available. "
                    + "Debt / equity is a multiple (x), not a percentage.\n\n");
            md.append("### Multi-year growth (CALCULATED)\n\n| Metric | Value | Period | Calculation | Input fields |\n")
                    .append("|---|---|---|---|---|\n");
            for (FinancialDataPoint p : List.of(summary.calculated().revenueCagrPercent(),
                    summary.calculated().netProfitCagrPercent())) {
                md.append("| ").append(p.metric()).append(" | ").append(value(p, conflicted)).append(" | ")
                        .append(p.period().label()).append(" | ")
                        .append(p.calculation() == null ? "" : p.calculation()).append(" | ")
                        .append(fields(p)).append(" |\n");
            }
            md.append("\n");
        }
    }

    private void renderHistory(StringBuilder md, HistoricalPerformance p, Mask conflicted) {
        md.append("Window: ").append(p.window().start()).append(" to ").append(p.window().end())
                .append(" (requested ").append(p.requestedYears()).append(" years, covered ")
                .append(p.actualYears().display()).append("). Basis: ").append(p.basis()).append(".\n\n");
        md.append("| Metric | Value | Date / period | Status |\n|---|---|---|---|\n");
        for (FinancialDataPoint point : List.of(p.startPrice(), p.endPrice(), p.totalReturnPercent(), p.cagrPercent(),
                p.periodHigh(), p.periodLow(), p.maxDrawdownPercent())) {
            md.append("| ").append(point.metric()).append(" | ").append(value(point, conflicted)).append(" | ")
                    .append(point.period().label()).append(" | ").append(status(point)).append(" |\n");
        }
        md.append("\nMaximum drawdown peak ").append(p.drawdownPeakDate()).append(", trough ")
                .append(p.drawdownTroughDate()).append(".\n\n");
        md.append("| Year | From | To | Close | Return |\n|---|---|---|---|---|\n");
        for (CalendarYearReturn year : p.calendarYearReturns()) {
            md.append("| ").append(year.year()).append(year.yearToDate() ? " (YTD, partial)" : "").append(" | ")
                    .append(year.fromDate() == null ? "-" : year.fromDate()).append(" | ").append(year.toDate())
                    .append(" | ").append(year.closingPrice().toPlainString()).append(" | ")
                    .append(year.returnPercent() == null ? "n/a (no prior year-end in window)"
                            : year.returnPercent().toPlainString() + "%")
                    .append(" |\n");
        }
        md.append("\n");
    }

    private void companyPoint(StringBuilder md, String label, FinancialDataPoint p, Mask conflicted) {
        md.append("| ").append(label).append(" | ").append(value(p, conflicted)).append(" | ").append(status(p))
                .append(" | ").append(raw(p, conflicted)).append(" | ")
                .append(p.source() != null && p.source().asOf() != null ? p.source().asOf().toString() : "UNKNOWN")
                .append(" | ").append(fields(p)).append(" |\n");
    }

    private void text(StringBuilder md, String label, String value, String field) {
        md.append("| ").append(label).append(" | ").append(value == null ? "UNAVAILABLE" : value)
                .append(" | REPORTED | - | - | ").append(field).append(" |\n");
    }

    private String value(FinancialDataPoint p, Mask conflicted) {
        String shown = p.available() ? p.display() : "UNAVAILABLE - " + p.unavailableReason();
        if (!conflicted.covers(p)) {
            return shown;
        }
        return conflicted.forModel() ? WITHHELD_FOR_MODEL : shown + CONFLICT_TAG;
    }

    private String raw(FinancialDataPoint p, Mask conflicted) {
        return conflicted.forModel() && conflicted.covers(p) ? "-" : raw(p);
    }

    private String status(FinancialDataPoint p) {
        return p.available() ? p.calculationStatus().name() : p.availability().name();
    }

    private String raw(FinancialDataPoint p) {
        if (p.rawValue() == null) {
            return "-";
        }
        return p.rawValue().toPlainString() + " (" + (p.providerUnit() == null ? "meaning unverified" : p.providerUnit()) + ")";
    }

    private String fields(FinancialDataPoint p) {
        return String.join(", ", p.dependsOnFields());
    }
}
